version: '2'
services:
    pfm-app:
        image: pfm
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://pfm-postgresql:5432/pfm
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pfm-postgresql:
        extends:
            file: postgresql.yml
            service: pfm-postgresql
